name: New Release on Tag Push

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  get_tag_info:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.get_tag_name.outputs.tag_name }}
      tag_message: ${{ steps.get_tag_message.outputs.tag_message }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Tag Name
        id: get_tag_name
        run: |
          echo "tag_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "Tag Name: ${{ github.ref_name }}"
      - name: Get Tag Message
        id: get_tag_message
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          tm=$(git tag -l --format='%(contents:subject)' ${{ steps.get_tag_name.outputs.tag_name }})
          echo "Tag Message: $tm"
          echo "tag_message=$tm" >> $GITHUB_OUTPUT
      - name: Print Output
        run: |
          echo "Tag Name: ${{ steps.get_tag_name.outputs.tag_name }}"
          echo "Tag Message: ${{ steps.get_tag_message.outputs.tag_message }}"

  build_and_test:
    runs-on: macos-latest
    needs: get_tag_info

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.get_tag_info.outputs.tag_name }}

      - name: Print Xcode Version
        run: xcodebuild -version
      - uses: swift-actions/setup-swift@v3
      - name: Get swift version
        run: swift --version
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  create_release:
    permissions:
      contents: write
    needs: [get_tag_info, build_and_test]
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      uses: actions/create-release@v1
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
            tag_name: ${{ needs.get_tag_info.outputs.tag_name }}
            release_name: Release ${{ needs.get_tag_info.outputs.tag_name }}
            body: ${{ needs.get_tag_info.outputs.tag_message }}
